# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWt < Formula
  desc "Git worktree management tool"
  homepage "https://github.com/shogs/git-wt"
  version "0.3.2"

  on_macos do
    on_intel do
      url "https://github.com/shogs/git-wt/releases/download/v0.3.2/git-wt_0.3.2_Darwin_x86_64.tar.gz"
      sha256 "403176465db47ebcdb03316036c2e6647ad2b864636f046a47589444dd06bef9"

      def install
        bin.install "git-wt"
      end
    end
    on_arm do
      url "https://github.com/shogs/git-wt/releases/download/v0.3.2/git-wt_0.3.2_Darwin_arm64.tar.gz"
      sha256 "526854ca3bc6b93fef6221f93c50209bd835c3b76efc408c85623e3a092b67dc"

      def install
        bin.install "git-wt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shogs/git-wt/releases/download/v0.3.2/git-wt_0.3.2_Linux_x86_64.tar.gz"
        sha256 "9557352e4ef83064863108cb5adf95d4d807998cf46f91d09cd49517da521b88"

        def install
          bin.install "git-wt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shogs/git-wt/releases/download/v0.3.2/git-wt_0.3.2_Linux_arm64.tar.gz"
        sha256 "a0198aa7290121063e6a35f19d096a8ace68715c8289153456b3cb888979df91"

        def install
          bin.install "git-wt"
        end
      end
    end
  end

  test do
    system "#{bin}/git-wt", "--version"
  end
end
