# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWt < Formula
  desc "Git worktree management tool"
  homepage "https://github.com/shogs/git-wt"
  version "0.3.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shogs/git-wt/releases/download/v0.3.6/git-wt_0.3.6_Darwin_x86_64.tar.gz"
      sha256 "b0b1deccc5534a224e0d73253341142c156c30b75a4d4e037b60479603549e10"

      def install
        bin.install "git-wt"
      end
    end
    on_arm do
      url "https://github.com/shogs/git-wt/releases/download/v0.3.6/git-wt_0.3.6_Darwin_arm64.tar.gz"
      sha256 "a79e02ff5ed9e49ffe6ab8ad487f2e8331e91f8cf0ecc9a30afb3bfa6e024162"

      def install
        bin.install "git-wt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shogs/git-wt/releases/download/v0.3.6/git-wt_0.3.6_Linux_x86_64.tar.gz"
        sha256 "026f1c2c14865674b7620c172ab1f919a88d9ea1307f19f57e1b54d2aeedd7df"

        def install
          bin.install "git-wt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shogs/git-wt/releases/download/v0.3.6/git-wt_0.3.6_Linux_arm64.tar.gz"
        sha256 "75f7582e634d703d8e6784477cbe1f562d48c808479e5cf969de0e17d181f811"

        def install
          bin.install "git-wt"
        end
      end
    end
  end

  test do
    system "#{bin}/git-wt", "--version"
  end
end
