# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWt < Formula
  desc "Git worktree management tool"
  homepage "https://github.com/shogs/git-wt"
  version "0.3.11"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shogs/git-wt/releases/download/v0.3.11/git-wt_0.3.11_Darwin_x86_64.tar.gz"
      sha256 "b8a31690a274d20f4000fdc6cef9eb983340c908996b11610110ce83542191cc"

      def install
        bin.install "git-wt"
      end
    end
    on_arm do
      url "https://github.com/shogs/git-wt/releases/download/v0.3.11/git-wt_0.3.11_Darwin_arm64.tar.gz"
      sha256 "5bec9dd2103bb5c34f34a0dbfdc5c679c7bbb5c6bdfeb1b0ebd664e425386afc"

      def install
        bin.install "git-wt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shogs/git-wt/releases/download/v0.3.11/git-wt_0.3.11_Linux_x86_64.tar.gz"
        sha256 "244e300bc105f2f3259c6aa527bcd292e6c598f9570e15e9c720c46c7687cb08"

        def install
          bin.install "git-wt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shogs/git-wt/releases/download/v0.3.11/git-wt_0.3.11_Linux_arm64.tar.gz"
        sha256 "e157eff0d16ae3ef77da51cfbf4eec1d20cc2b6cc2ee29a0c93c83a506d3062e"

        def install
          bin.install "git-wt"
        end
      end
    end
  end

  test do
    system "#{bin}/git-wt", "--version"
  end
end
