# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWt < Formula
  desc "Git worktree management tool"
  homepage "https://github.com/shogs/git-wt"
  version "0.3.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shogs/git-wt/releases/download/v0.3.3/git-wt_0.3.3_Darwin_x86_64.tar.gz"
      sha256 "6920941c00b6ed868cb75596f11612fc5f8caec1067f8f77bd0223e5e4c73772"

      def install
        bin.install "git-wt"
      end
    end
    on_arm do
      url "https://github.com/shogs/git-wt/releases/download/v0.3.3/git-wt_0.3.3_Darwin_arm64.tar.gz"
      sha256 "a63a7538860a91b92a46b93e08f531c2e1bb5c8babaff67c48b404ced578d60a"

      def install
        bin.install "git-wt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shogs/git-wt/releases/download/v0.3.3/git-wt_0.3.3_Linux_x86_64.tar.gz"
        sha256 "085667c0e3b71f4dfc5f73160f6e405dbd0167e408f2fce3cb3445c50ab0caf1"

        def install
          bin.install "git-wt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shogs/git-wt/releases/download/v0.3.3/git-wt_0.3.3_Linux_arm64.tar.gz"
        sha256 "bcb49a47e415cbeb933e24f2a51ff6db97e0da98c1ae073314a2e7525a5dfdda"

        def install
          bin.install "git-wt"
        end
      end
    end
  end

  test do
    system "#{bin}/git-wt", "--version"
  end
end
